---
grafana_ini:
  security:
    admin_user: admin
    admin_password: "{{ vault_grafana_password }}"

  auth:
    anonymous:
      org_name: "Main Org."
      org_role: Viewer

  metrics:
    enabled: true

grafana_datasources:
  - name: "Prometheus"
    type: "prometheus"
    access: "proxy"
    url: "http://{{ ansible_host | default(inventory_hostname) }}:9090"
    isDefault: true

grafana_dashboards: []
